name: "34-frontend-mutation-testing: Stryker JS Mutation Testing (JavaScript/Jest)"

on:
  workflow_dispatch:
  pull_request:
    paths: [frontend/**]
  push:
    branches: [ main ]
    paths: ['frontend/**']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "America/Los_Angeles"
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./frontend
      - run: npx stryker run
        working-directory: ./frontend
